// Code generated by "stringer -type=lifecycleStage -linecomment"; DO NOT EDIT.

package wavestate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stageOpen-0]
	_ = x[stageClosed-1]
	_ = x[stageFlushing-2]
	_ = x[stageDone-3]
}

const _lifecycleStage_name = "OpenClosedFlushingDone"

var _lifecycleStage_index = [...]uint8{0, 4, 10, 18, 22}

func (i lifecycleStage) String() string {
	if i < 0 || i >= lifecycleStage(len(_lifecycleStage_index)-1) {
		return "lifecycleStage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _lifecycleStage_name[_lifecycleStage_index[i]:_lifecycleStage_index[i+1]]
}
