#!/bin/bash

set -e

echo "$0: Entering directory \``pwd`'"
goimports -w .
gofmt -s -w .

find . -type f -name go.mod -print0 | while IFS= read -r -d '' file; do (
    set -e
    cd "${file%/*}"
    echo "$0: Entering directory \``pwd`'"
    set -x
    go mod tidy
    go vet ./...
    go test -short ./...
    go generate ./...
    go-licenses check --include_tests $(go-licenses-ignore .) ./...
); echo; done

echo "$0: Entering directory \``pwd`'"

set -x
golangci-lint config verify
golangci-lint run
! git status --porcelain -uno | grep '^[^ ][^ ]'
