// Copyright (c) Peter Newcomb. All rights reserved.
// Licensed under the MIT License.

package psg

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"github.com/petenewcomb/psg-go/internal/trace"

	"github.com/petenewcomb/psg-go/internal/cpstate"
	"github.com/petenewcomb/psg-go/internal/heap"
	"github.com/petenewcomb/psg-go/internal/jobstate"
	"github.com/petenewcomb/psg-go/internal/rdvq"
	"github.com/petenewcomb/psg-go/internal/timerp"
	"github.com/petenewcomb/psg-go/internal/workq"
	"github.com/petenewcomb/psg-go/psgopt"
)

// CombinerPool manages a pool of goroutines that execute combiners.
// It handles concurrency limits, spawning new goroutines, and reusing existing ones.
type CombinerPool struct {
	j *Job

	// CombinerPoolState hosts the data and core logic for managing the pool of
	// goroutines to maximize throughput with the minimum number of goroutines
	// and therefore duplication of individual combiners.
	state cpstate.CombinerPoolState

	// Work posting uses two-tier delivery via combineQueue:
	// 1. Try immediate delivery to waiting receivers
	// 2. If no waiting receiver, use sender's outbox and block if needed
	//
	// Primary goroutines register for immediate delivery, while the spare
	// goroutine uses PopFrontExcessFunc to process outboxes and shared channel
	// without registering for immediate delivery.
	//
	// Only one goroutine at a time can elect itself "spare" for scaling.
	combineQueue workq.Pending
	spareElected atomic.Bool

	// If there are tasks waiting to post work to combineQueue, waitingCombines
	// is non-zero. If a scatter determines that there are waiting combines, it
	// will block to apply backpressure by registering with waitingScatters.
	waitingCombines jobstate.InFlightCounter
	waitingScatters workq.Waiters

	// Work that the pool has already committed to do because it was pulled from
	// combineQueue or generated by combiners
	workQueue workq.Accepted
}

// NewCombinerPool creates a new CombinerPool bound to the specified job.
//
// Panics if the job is nil or in the done state.
//
//nolint:contextcheck // background context used only for tracing
func NewCombinerPool(job *Job, options ...psgopt.CombinerPoolOption) *CombinerPool {
	traceRegion := "NewCombinerPool"

	// Check if the job is done
	job.panicIfDone()
	cp := &CombinerPool{
		j: job,
	}

	// Apply default configuration
	cp.state.SetOptions(
		psgopt.WithConcurrencyBounds(0, -1), // unlimited by default
		psgopt.WithHighUtilizationThreshold(psgopt.DefaultCombinerPoolHighUtilizationThreshold),
		psgopt.WithMeasurementTimeConstant(psgopt.DefaultCombinerPoolMeasurementTimeConstant),
		psgopt.WithHistoryRetentionPeriod(psgopt.DefaultCombinerPoolHistoryRetentionPeriod),
		psgopt.WithMinThroughputROI(psgopt.DefaultCombinerPoolMinThroughputROI),
		psgopt.WithGrowthFactors(psgopt.DefaultCombinerPoolAggressiveGrowthFactor, psgopt.DefaultCombinerPoolConservativeGrowthFactor),
		psgopt.WithIdleTimeout(psgopt.DefaultCombinerPoolIdleTimeout),
	)

	// Apply user options
	cp.state.SetOptions(options...)

	cp.combineQueue.Init()
	cp.waitingScatters.Init()
	cp.workQueue.Init()

	trace.Logf(context.Background(), traceRegion, "CombinerPool=%p, job=%p, state=%p, combineQueue=%p, waitingCombines=%p, waitingScatters=%p, workQueue=%p",
		cp, job, &cp.state, &cp.combineQueue, &cp.waitingCombines, &cp.waitingScatters, &cp.workQueue)

	return cp
}

// checkInitialized panics if the CombinerPool was not properly initialized via NewCombinerPool
func (cp *CombinerPool) checkInitialized() {
	if cp.j == nil {
		panic("CombinerPool not initialized: must use NewCombinerPool")
	}
}

// combineOutboxKey returns a unique identifier for this CombinerPool for combine outbox mapping.
func (cp *CombinerPool) combineOutboxKey() outboxKey[workq.WorkFunc] {
	return cp
}

// SetOptions applies the given configuration options to the pool.
func (cp *CombinerPool) SetOptions(options ...psgopt.CombinerPoolOption) {
	cp.checkInitialized()
	cp.state.SetOptions(options...)
}

func (cp *CombinerPool) postCombine(ctx context.Context, outbox *rdvq.Outbox[workq.WorkFunc], combineFn boundCombineFunc) {
	traceRegion := "CombinerPool.postCombine"
	defer trace.StartRegion(ctx, traceRegion).End()

	workID := workIDCounter.Add(1)
	trace.Logf(ctx, traceRegion, "CombinerPool=%p, outbox=%p, workID=%d", ctx, outbox, workID)

	if cp.state.MaybeSpawnGoroutine() {
		cp.spawnNewCombiner(ctx)
	}

	workFn := cp.newCombineWork(combineFn, workID, false)
	cp.combineQueue.PushBackFunc(outbox, workFn, func(outboxCh chan<- workq.WorkFunc) rdvq.SelectResult {
		// Fallback to slow path when outbox would block
		return cp.postCombineSlow(ctx, outboxCh, combineFn, workID)
	})
}

func (cp *CombinerPool) newCombineWork(combineFn boundCombineFunc, workID int64, waitersIncremented bool) workq.WorkFunc {
	return func(ctx context.Context, ex workq.Execution) error {
		traceRegion := "CombinerPool.newCombineWork.workFn"
		defer trace.StartRegion(ctx, traceRegion).End()
		trace.Logf(ctx, traceRegion, "CombinerPool=%p, workID=%d", ctx, workID)

		ex.Starting()
		if waitersIncremented {
			cp.releaseWaiters()
		}

		workerCtx, meta := cp.j.ctxMeta(ctx)
		cw := meta.executionEnvironment.(*cpWorker)
		cw.WithQueueFunc(ex.Queue, func() {
			cw.executeCombine(workerCtx, combineFn)
		})
		return nil
	}
}

//nolint:contextcheck // background context used only for tracing
func (cp *CombinerPool) releaseWaiters() {
	traceRegion := "CombinerPool.releaseWaiters"
	defer trace.StartRegion(context.Background(), traceRegion).End()

	if cp.waitingCombines.Decrement() {
		// No more waiting combines, so release all remaining
		// combine waiters
		cp.waitingScatters.NotifyAll()
	}
}

func (cp *CombinerPool) postCombineSlow(ctx context.Context, outboxCh chan<- workq.WorkFunc, combineFn boundCombineFunc, workID int64) rdvq.SelectResult {
	traceRegion := "CombinerPool.postCombineSlow"
	defer trace.StartRegion(ctx, traceRegion).End()
	trace.Logf(ctx, traceRegion, "outboxCh=%d", outboxCh)

	// We don't attempt the primary channel alone here since both fast paths
	// failed, meaning both primary and spare goroutines are likely busy. At
	// this point spillage to spare is warranted, so we use
	// first-come-first-served among whatever becomes available.

	var workFn workq.WorkFunc
	defer func() {
		// If we incremented waiters but didn't successfully send to a channel,
		// we must release the waiters ourselves
		if workFn != nil {
			cp.releaseWaiters()
		}
	}()

	for {
		spawnWaitCh := cp.state.ShouldSpawnGoroutine()
		if spawnWaitCh == nil {
			cp.spawnNewCombiner(ctx)
		}

		// If we get here, the primary and spare channels were busy and we
		// hit the limit of how many combiner tasks we can launch or need to
		// wait before we can spawn another. Increment the waiting task count to
		// signal Scatter to apply backpressure.
		if workFn == nil {
			cp.waitingCombines.Increment()
			workFn = cp.newCombineWork(combineFn, workID, true)
		}

		// Block until we can post or it's time to retry
		trace.Logf(ctx, traceRegion, "entering select: outboxCh=%p, spawnWaitCh=%p", outboxCh, spawnWaitCh)
		select {
		case outboxCh <- workFn:
			workFn = nil // Successfully sent, don't release waiters in defer
			trace.Logf(ctx, traceRegion, "received workFn from outboxCh=%d", outboxCh)
			return rdvq.SelectOutboxFilled
		case <-spawnWaitCh:
			trace.Logf(ctx, traceRegion, "received signal from spawnWaitCh=%d", spawnWaitCh)
			// Loop to check if we need to spawn a new goroutine
		case <-ctx.Done():
			trace.Logf(ctx, traceRegion, "received context done signal")
			return rdvq.SelectAborted
		}
	}
}

func (cp *CombinerPool) spawnNewCombiner(ctx context.Context) {
	traceRegion := "CombinerPool.spawnNewCombiner"
	trace.Logf(ctx, traceRegion, "starting new combiner goroutine")

	j := cp.j
	j.wg.Add(1)
	go func() { //nolint:contextcheck // must use job context
		defer j.wg.Done()

		// Create the base goroutine context
		goroutineCtx, cancelGoroutineCtx := context.WithCancel(j.ctx)
		// deferred call to cancel below

		traceRegion := "CombinerPool.goroutine"
		defer trace.StartRegion(goroutineCtx, traceRegion).End()
		trace.Logf(goroutineCtx, traceRegion, "CombinerPool=%p", cp)

		// Minimize the number of channels on which this goroutine must repeatedly
		// retrieve and select to reduce contention.
		doneCh := make(chan struct{})
		var doneErr error
		var doneWg sync.WaitGroup
		doneWg.Add(1)
		go func() {
			defer doneWg.Done()
			select {
			case <-j.state.Done():
				doneErr = ErrJobDone
			case <-goroutineCtx.Done():
				doneErr = goroutineCtx.Err()
			}
			close(doneCh)
		}()
		defer func() {
			trace.Logf(context.Background(), traceRegion, "canceling goroutine context")
			cancelGoroutineCtx()
			doneWg.Wait()
		}()

		worker := &cpWorker{
			cp:     cp,
			doneCh: doneCh,
			doneErr: func() error {
				return doneErr
			},
		}

		ctx, _ := j.ensureCtxMeta(goroutineCtx,
			func(ctx context.Context, meta *ctxMeta) context.Context {
				meta.ctxType = combineContext
				meta.executionEnvironment = worker
				return ctx
			},
		)

		// Create the dedicated outbox for this combiner goroutine to emit gathers to the job
		worker.emitGatherOutbox = OutboxFor[workq.WorkFunc](&worker.outboxMap, j.gatherOutboxKey())

		trace.Logf(ctx, traceRegion, "cpWorker=%p, combinerMap=%p, emitGatherOutbox=%p", worker, &worker.combinerMap, worker.emitGatherOutbox)

		cp.state.GoroutineStarted()
		defer cp.state.GoroutineExited()

		for {
			if worker.idleTimer == nil {
				if cp.spareElected.CompareAndSwap(false, true) {
					worker.idleTimer = timerp.Get()
					defer func() { //nolint:gocritic // can execute only once due to CAS
						cp.spareElected.Store(false)
						timerp.Put(worker.idleTimer)
					}()
				}
			}

			err := cp.workQueue.ExecuteOne(ctx, worker.AddWork)
			if err != nil {
				if errors.Is(err, workq.ErrEndOfWork) {
					trace.Logf(ctx, traceRegion, "at end of work")
					break
				}
				if errIn(err, ErrJobDone, context.Canceled, context.DeadlineExceeded) {
					trace.Logf(ctx, traceRegion, "exiting early with err=%v", err)
					return
				}
				if err != nil {
					panic(fmt.Sprintf("combiner goroutine received unexpected error: %v", err))
				}
			}
		}

		traceRegion += ".shutdown"
		defer trace.StartRegion(ctx, traceRegion).End()

		// Flush combiners as needed when this goroutine terminates.
		worker.flushAll(ctx)

		for {
			// Process any work items that were created during the flush operation
			err := cp.workQueue.ExecuteOne(ctx, nil)
			if err != nil {
				if errors.Is(err, workq.ErrEndOfWork) {
					trace.Logf(ctx, traceRegion, "exiting at end of work")
					break
				}
				if errIn(err, ErrJobDone, context.Canceled, context.DeadlineExceeded) {
					trace.Logf(ctx, traceRegion, "exiting with err=%v", err)
					return
				}
				if err != nil {
					panic(fmt.Sprintf("combiner goroutine received unexpected error at shutdown: %v", err))
				}
			}
		}
	}()
}

type boundCombineFunc func(ctx context.Context, cm *combinerMap, queueWork workq.QueueWorkFunc, gatherOutbox *rdvq.Outbox[workq.WorkFunc])

type halfBoundCombineFunc[I any] func(ctx context.Context, input I, inputErr error)

type boundCombiner struct {
	CombineFn     any
	FlushFn       func(ctx context.Context)
	FirstCombine  time.Time // When first unflushed input was received (for maxHoldTime)
	FlushDeadline time.Time // The earliest time this combiner should be flushed
	heapPosition  int       // Position in the deadline heap, 0 if not in heap
}

// Less implements heap.Item interface
func (bc *boundCombiner) Less(other *boundCombiner) bool {
	return bc.FlushDeadline.Before(other.FlushDeadline)
}

// SetPosition implements heap.Item interface
func (bc *boundCombiner) SetPosition(position int) {
	bc.heapPosition = position
}

// Position implements heap.Item interface
func (bc *boundCombiner) Position() int {
	return bc.heapPosition
}

type combinerMap struct {
	m         map[combinerMapKey]*boundCombiner
	deadlines heap.Heap[*boundCombiner]
}

type combinerMapKey struct {
	Job     *Job
	Combine any
}

func getCombineFunc[I, O any](ctx context.Context, cm *combinerMap, cp *CombinerPool, c *CombineOp[I, O], queueWork workq.QueueWorkFunc, emitGatherOutbox *rdvq.Outbox[workq.WorkFunc]) halfBoundCombineFunc[I] {
	j := cp.j
	k := combinerMapKey{
		Job:     j,
		Combine: c,
	}
	bc := cm.m[k]
	var combineFn halfBoundCombineFunc[I]
	if bc != nil {
		combineFn = bc.CombineFn.(halfBoundCombineFunc[I])
	} else {
		emit := func(ctx context.Context, output O, outputErr error) {
			traceRegion := "CombinerPool.emit"
			defer trace.StartRegion(ctx, traceRegion).End()

			if outputErr != nil {
				trace.Logf(ctx, traceRegion, "emitting err=%v", outputErr)
			}

			j.state.IncrementWork()

			// Bind the gatherFn to the combiner output
			gatherFn := func(ctx context.Context) error {
				defer j.state.DecrementWork()
				return c.gatherOp.gatherFn(ctx, output, outputErr)
			}

			gatherWorkFn := j.newGatherWork(gatherFn)
			outboxFn := func(ctx context.Context, fn func(*workq.Outbox)) {
				_, meta := j.ctxMeta(ctx)
				meta.WithOutbox(j.gatherOutboxKey(), fn)
			}
			postWorkFn := j.gatherQueue.NewPostOfferWork(gatherWorkFn, outboxFn)
			queueWork(postWorkFn)
		}

		combiner := func() Combiner[I, O] {
			traceRegion := "CombinerPool.newCombiner"
			defer trace.StartRegion(ctx, traceRegion).End()

			panicked := true
			defer func() {
				if panicked {
					emit(ctx, *new(O), ErrCombinerFactoryPanicked)
				}
			}()
			combiner := c.newCombiner()
			panicked = false
			if combiner == nil {
				emit(ctx, *new(O), ErrCombinerFactoryReturnedNil)
				return &errCombiner[I, O]{err: ErrCombinerFactoryReturnedNil}
			}

			trace.Logf(ctx, traceRegion, "CombineOp=%p returning new combiner=%v", c, combiner)
			return combiner
		}()

		// Initialize the map if needed
		if cm.m == nil {
			cm.m = make(map[combinerMapKey]*boundCombiner)
		}

		// Create the boundCombiner first
		bc = &boundCombiner{}

		// Define the combineFn with access to bc
		combineFn = func(ctx context.Context, input I, inputErr error) {
			traceRegion := "CombinerPool.combineFn"
			defer trace.StartRegion(ctx, traceRegion).End()

			now := time.Now()

			// If this is the first combine since last flush, record the time
			if bc.FirstCombine.IsZero() {
				bc.FirstCombine = now
			}

			// Calculate flush deadline based on min/max hold times
			var deadline time.Time

			// Calculate minHoldTime deadline (time since this combine operation)
			if c.minHoldTime >= 0 {
				deadline = now.Add(c.minHoldTime)
			}

			// Calculate maxHoldTime deadline (time since first combine)
			if c.maxHoldTime >= 0 {
				maxDeadline := bc.FirstCombine.Add(c.maxHoldTime)
				// Use maxDeadline if it's earlier or if no min deadline yet
				if deadline.IsZero() || maxDeadline.Before(deadline) {
					deadline = maxDeadline
				}
			}

			cm.UpdateFlushDeadline(bc, deadline)

			didNotPanic := false
			defer func() {
				if !didNotPanic {
					// Just in case the panic is otherwise suppressed
					emit(ctx, *new(O), ErrCombinePanicked)
				}
			}()

			trace.Logf(ctx, traceRegion, "calling Combine on combiner=%v", combiner)
			combiner.Combine(ctx, input, inputErr, emit)
			didNotPanic = true
		}

		// Store the combineFn in the boundCombiner
		bc.CombineFn = combineFn

		// Define the FlushFn with access to bc
		bc.FlushFn = func(ctx context.Context) {
			traceRegion := "CombinerPool.flushFn"
			defer trace.StartRegion(ctx, traceRegion).End()

			// Reset FirstCombine for next batch, but keep combiner in map for reuse
			bc.FirstCombine = time.Time{}

			didNotPanic := false
			defer func() {
				if !didNotPanic {
					// Just in case the panic is otherwise suppressed
					emit(ctx, *new(O), ErrCombinerFlushPanicked)
				}
			}()

			trace.Logf(ctx, traceRegion, "calling Flush on combiner=%v", combiner)
			combiner.Flush(ctx, emit)
			didNotPanic = true
		}

		// Add the boundCombiner to the map
		cm.m[k] = bc
	}
	return combineFn
}

func (cm *combinerMap) UpdateFlushDeadline(bc *boundCombiner, deadline time.Time) {
	bc.FlushDeadline = deadline
	if deadline.IsZero() {
		cm.deadlines.Remove(bc)
	} else {
		cm.deadlines.Push(bc)
	}
}

func (cm *combinerMap) NextToFlush() *boundCombiner {
	if cm.deadlines.Len() == 0 {
		return nil
	}
	// Peek at the earliest deadline
	return cm.deadlines.Peek()
}

// Remove removes a combiner from both the map and the deadline heap
func (cm *combinerMap) Remove(k combinerMapKey, bc *boundCombiner) {
	// Remove from the heap if it's there
	_ = cm.deadlines.Remove(bc)
	// Remove from the map
	delete(cm.m, k)
}

func (cm *combinerMap) FlushAll(ctx context.Context) {
	traceRegion := "combinerMap.FlushAll"
	defer trace.StartRegion(ctx, traceRegion).End()
	trace.Logf(ctx, traceRegion, "len=%d", len(cm.m))
	for _, bc := range cm.m {
		bc.FlushFn(ctx)
	}
	cm.m = nil
	cm.deadlines = heap.Heap[*boundCombiner]{} // Reset to zero value
}
