// Copyright (c) Peter Newcomb. All rights reserved.
// Licensed under the MIT License.

package psg

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/petenewcomb/psg-go/internal/jobstate"
	"github.com/petenewcomb/psg-go/internal/nbcq"
	"github.com/petenewcomb/psg-go/internal/rdvq"
	"github.com/petenewcomb/psg-go/internal/trace"

	"github.com/petenewcomb/psg-go/internal/cpstate"
	"github.com/petenewcomb/psg-go/internal/omnipool"
	"github.com/petenewcomb/psg-go/internal/timerp"
	"github.com/petenewcomb/psg-go/internal/workq"
	"github.com/petenewcomb/psg-go/psgopt"
)

// CombinerPool manages a pool of goroutines that execute combiners.
// It handles concurrency limits, spawning new goroutines, and reusing existing ones.
type CombinerPool struct {
	job *Job

	// CombinerPoolState hosts the data and core logic for managing the pool of
	// goroutines to maximize throughput with the minimum number of goroutines
	// and therefore duplication of individual combiners.
	state    cpstate.CombinerPoolState
	inFlight jobstate.InFlightCounter

	combineQueue workq.Pending

	abandonedCombiners nbcq.Queue[*activeCombinerMap]

	// If there are tasks waiting to post work to combineQueue, the governor
	// will block new top-level scatters, thereby applying backpressure to
	// regulate the system.
	governor workq.Governor

	// Work that the pool has already committed to do because it was pulled from
	// combineQueue or generated by combiners
	workQueue workq.Accepted

	unmetDemandFn workq.RenotifyFunc // avoid closure reallocation
}

// NewCombinerPool creates a new CombinerPool bound to the specified job.
//
// Panics if the job is nil or in the done state.
//
//nolint:contextcheck // background context used only for tracing
func NewCombinerPool(job *Job, options ...psgopt.CombinerPoolOption) *CombinerPool {
	traceRegion := "NewCombinerPool"
	defer trace.StartRegion(context.Background(), traceRegion).End()

	// Check if the job is done
	job.panicIfDone()

	cp := &CombinerPool{
		job: job,
	}

	cp.unmetDemandFn = func() { cp.spawnNewGoroutine() }

	trace.Logf(context.Background(), traceRegion,
		"CombinerPool=%p, job=%p, state=%p, combineQueue=%p, governor=%p, workQueue=%p",
		cp, job, &cp.state, &cp.combineQueue, &cp.governor, &cp.workQueue)

	cp.combineQueue.Init()
	cp.abandonedCombiners.Init()
	cp.governor.Init()
	cp.workQueue.Init()
	cp.state.Init()

	// Apply default configuration
	cp.state.SetOptions(
		psgopt.WithMaxConcurrency(-1), // unlimited by default
		psgopt.WithIdleTimeout(psgopt.DefaultCombinerPoolIdleTimeout),
		psgopt.WithIdleJitter(psgopt.DefaultCombinerPoolIdleJitter),
	)

	// Apply user options
	cp.state.SetOptions(options...)

	return cp
}

// checkInitialized panics if the CombinerPool was not properly initialized via NewCombinerPool
func (cp *CombinerPool) checkInitialized() {
	if cp.job == nil {
		panic("CombinerPool not initialized: must use NewCombinerPool")
	}
}

// SetOptions applies the given configuration options to the pool.
func (cp *CombinerPool) SetOptions(options ...psgopt.CombinerPoolOption) {
	cp.checkInitialized()
	cp.state.SetOptions(options...)
}

//nolint:contextcheck // goroutine will use job context
func (cp *CombinerPool) spawnNewGoroutine() {
	traceRegion := "CombinerPool.spawnNewGoroutine"
	trace.Logf(context.Background(), traceRegion,
		"CombinerPool=%p starting new goroutine", cp)
	wg := &cp.job.wg
	wg.Add(1)
	go func() {
		defer wg.Done()
		cp.goroutine()
	}()
}

func (cp *CombinerPool) goroutine() {
	var doneWg sync.WaitGroup
	doneCh := make(chan struct{})
	var doneErr error
	worker := &cpWorker{
		cp:     cp,
		doneCh: doneCh,
		doneErr: func() error {
			return doneErr
		},
		activeCombiners: &activeCombinerMap{},
	}

	traceRegion := "CombinerPool.goroutine"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "CombinerPool=%p, worker=%p", cp, worker)

	j := cp.job

	// Create the base goroutine context
	ctx, cancel := context.WithCancel(j.ctx)
	ctx, _ = j.ensureCtxMeta(ctx,
		func(ctx context.Context, meta *ctxMeta) context.Context {
			meta.ctxType = combineContext
			meta.executionEnvironment = worker
			return ctx
		},
	)

	defer func() {
		trace.Logf(context.Background(), traceRegion, "canceling context")
		cancel()
		doneWg.Wait()
	}()

	// Minimize the number of channels on which this goroutine must repeatedly
	// retrieve and select to reduce contention.
	doneWg.Add(1)
	go func() {
		defer doneWg.Done()
		select {
		case <-j.state.Done():
			doneErr = ErrJobDone
		case <-ctx.Done():
			doneErr = ctx.Err()
		}
		close(doneCh)
	}()

	trace.Logf(ctx, traceRegion, "cpWorker=%p, combinerMap=%p",
		worker, &worker.activeCombiners)

	worker.idleTimer = timerp.Get()
	defer timerp.Put(worker.idleTimer)

	cp.state.GoroutineStarted()

	addWorkFn := worker.AddWork

	mergeAbandonedCombiners := func() {
		for {
			abandonedCombiners, _ := cp.abandonedCombiners.TryPopFront()
			if abandonedCombiners == nil {
				break
			}
			worker.activeCombiners.Merge(abandonedCombiners)
			worker.activeCombiners.FlushExcess(ctx, worker.Sender(), cp.state.LiveGoroutineCount())
			if worker.nextJobFlushCh == nil {
				// Make sure the job won't terminate before the combiner is flushed
				worker.nextJobFlushCh, worker.unregisterAsJobFlusher = worker.cp.job.state.RegisterFlusher()
			}
		}
	}

	confirmEndOfWork := false
	for {
		confirmingEndOfWork := confirmEndOfWork
		confirmEndOfWork = false

		mergeAbandonedCombiners()

		err := cp.workQueue.ExecuteOne(ctx, addWorkFn, cp.unmetDemandFn)
		switch {
		case err == nil:
		case errors.Is(err, workq.ErrEndOfWork):
			if confirmingEndOfWork {
				trace.Logf(ctx, traceRegion, "last goroutine at end of work, flushing combiners")
				if !worker.flushAll(ctx) {
					if cp.state.GoroutineExiting() {
						trace.Logf(ctx, traceRegion, "last goroutine exiting")
					} else {
						trace.Logf(ctx, traceRegion, "no-longer-last goroutine exiting")
					}
					return
				}
			}
			if cp.state.GoroutineExiting() {
				// This is the last goroutine running. Keep running a bit longer
				// to confirm that there's nothing more to do
				cp.state.GoroutineRestarted()
				confirmEndOfWork = cp.inFlight.IsZero()
			} else {
				trace.Logf(ctx, traceRegion, "goroutine exiting")
				// Stash active combiners for the next spare goroutine to pick up.
				cp.abandonedCombiners.PushBack(worker.activeCombiners)
				if worker.nextJobFlushCh != nil {
					worker.nextJobFlushCh = nil
					worker.unregisterAsJobFlusher()
				}
				return
			}
		case errIn(err, ErrJobDone, context.Canceled, context.DeadlineExceeded):
			trace.Logf(ctx, traceRegion, "exiting with err=%v", err)
			// Do NOT call GoroutineExiting() here. The Job is shutting down, so
			// goroutine accounting no longer matters. Additionally, this goroutine
			// may have already called GoroutineExiting() then GoroutineRestarted()
			// on the ErrEndOfWork path above, and calling it again would cause
			// double-decrement.
			return
		default:
			panic(fmt.Sprintf("combiner goroutine received unexpected error: %v", err))
		}
	}
}

type combinePostWork struct {
	jobWork
	pool *CombinerPool
	work boundCombineWork
}

func (w *combinePostWork) Init(group workq.GroupID, pool *CombinerPool, work boundCombineWork) {
	w.jobWork.Init(group, pool.job)
	w.pool = pool
	w.work = work
}

func (w *combinePostWork) Execute(ctx context.Context, ex workq.Execution) error {
	traceRegion := "combinePostWork.Execute"
	defer trace.StartRegion(ctx, traceRegion).End()
	trace.Logf(ctx, traceRegion, "%v", w)

	posted, err := func() (bool, error) {
		// Discover outbox from execution environment
		ctx, meta := w.pool.job.ctxMeta(ctx)

		spawnWaiters := &w.pool.state.SpawnNotifier().Waiters

		maybeSpawn := func() {
			if w.pool.state.ShouldSpawnGoroutine() {
				w.pool.spawnNewGoroutine()
			}
		}

		waiting := func() {
			// Call Waiting on the nested combineWork to notify the governor
			w.work.Waiting(&w.pool.governor)

			maybeSpawn()
		}

		tryPost := func() bool {
			// Try non-blocking post - can be retried if it fails
			return w.pool.combineQueue.TryPushBack(meta.Sender(), w.work, maybeSpawn)
		}

		for {
			if tryPost() {
				return true, nil
			}

			if !ex.ShouldBlockOrPostpone() {
				return false, nil
			}

			if !meta.ShouldBlock() {
				// We expect to be queued and called again, so listen and don't block
				ex.AddToListeners(w.pool.combineQueue.ListenersFor(meta.Sender()))
				// AddToListeners to be notified when spawning conditions change
				ex.AddToListeners(&w.pool.state.SpawnNotifier().Listeners)

				// Check again after registering for notification, but return
				// and expect to be called again if needed
				posted := tryPost()
				if !posted {
					waiting()
				}
				trace.Logf(ctx, traceRegion, "meta.QueueFunc() != nil, posted=%v", posted)
				return posted, nil
			}

			posted := true
			var err error
			shouldWait := func() bool {
				return !tryPost()
			}
			// Can ignore the returned renotifyFn since it will always be nil
			spawnWaiters.WaitFunc(meta.Waiter(), shouldWait, func(spawnWaitInbox *rdvq.WaitInbox) {

				w.pool.combineQueue.PushBackFunc(meta.Sender(), w.work, maybeSpawn, func(outbox *rdvq.Outbox[workq.Work]) {
					// Slow path, posting no longer implicit
					posted = false

					// Really going to block now
					ex.Blocking()

					waiting()

					outboxCh := outbox.Ch()
					spawnWaitCh := spawnWaitInbox.Ch()
					trace.Logf(ctx, traceRegion,
						"entering select: outbox=%p, outboxCh=%p, spawnWaitInbox=%p, spawnWaitCh=%p",
						outbox, outboxCh, spawnWaitInbox, spawnWaitCh)
					select {
					case outboxCh <- w.work:
						outbox.Filled()
						posted = true
						trace.Logf(ctx, traceRegion, "delivered value into outbox=%p, outboxCh=%p", outbox, outboxCh)
					case <-spawnWaitCh:
						// Didn't need to capture the renotifyFn because we always check ShouldSpawnGoroutine
						spawnWaitInbox.Emptied()
						trace.Logf(ctx, traceRegion,
							"received signal from spawnWaitInbox=%p, spawnWaitCh=%p", spawnWaitInbox, spawnWaitCh)
						if w.pool.state.ShouldSpawnGoroutine() {
							w.pool.spawnNewGoroutine()
						}
					case <-ctx.Done():
						trace.Logf(ctx, traceRegion, "received context done signal")
						err = ctx.Err()
					}
				})
			})
			trace.Logf(ctx, traceRegion, "meta.ShouldBlock(), posted=%v, err=%v", posted, err)
			if posted || err != nil {
				return posted, err
			}
		}
	}()

	if posted {
		ex.Starting() // Signal success only if we actually posted
		w.work = nil  // Clear the work reference since it's now owned by the queue

		// Now that the work is in the queue, make sure there's a goroutine to
		// pick it up
		trace.Logf(ctx, traceRegion, "calling ShouldSpawnFirstGoroutine")
		if w.pool.state.ShouldSpawnFirstGoroutine() {
			trace.Logf(ctx, traceRegion, "spawning first goroutine")
			w.pool.spawnNewGoroutine()
		} else {
			trace.Logf(ctx, traceRegion, "no need to spawn first goroutine")
		}
	}
	return err
}

//nolint:contextcheck // background context used only for tracing
func (w *combinePostWork) Free() {
	traceRegion := "combinePostWork.Free"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "%v", w)

	// Free the nested work item if we still own it
	if w.work != nil {
		trace.Logf(context.Background(), traceRegion, "w.work.Free()")
		w.work.Free()
		w.work = nil
	}

	w.Close(w.pool.job)
	combinePostWorkPool.Put(w)
}

var combinePostWorkPool = omnipool.For[combinePostWork]()

//nolint:contextcheck // background context used only for tracing
func (cp *CombinerPool) newCombinePostWork(group workq.GroupID, bc boundCombineWork) *combinePostWork {
	traceRegion := "CombinerPool.newCombinePostWork"

	w := combinePostWorkPool.Get()
	w.Init(group, cp, bc)

	trace.Logf(context.Background(), traceRegion, "CombinerPool=%p created %v", cp, w)
	return w
}
