// Copyright (c) Peter Newcomb. All rights reserved.
// Licensed under the MIT License.

package psg

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"github.com/petenewcomb/psg-go/internal/rdvq"
	"github.com/petenewcomb/psg-go/internal/trace"

	"github.com/petenewcomb/psg-go/internal/cpstate"
	"github.com/petenewcomb/psg-go/internal/omnipool"
	"github.com/petenewcomb/psg-go/internal/timerp"
	"github.com/petenewcomb/psg-go/internal/workq"
	"github.com/petenewcomb/psg-go/psgopt"
)

// CombinerPool manages a pool of goroutines that execute combiners.
// It handles concurrency limits, spawning new goroutines, and reusing existing ones.
type CombinerPool struct {
	job *Job

	// CombinerPoolState hosts the data and core logic for managing the pool of
	// goroutines to maximize throughput with the minimum number of goroutines
	// and therefore duplication of individual combiners.
	state cpstate.CombinerPoolState

	// Work posting uses two-tier delivery via combineQueue:
	// 1. Try immediate delivery to waiting receivers
	// 2. If no waiting receiver, use sender's outbox and block if needed
	//
	// Primary goroutines register for immediate delivery, while the spare
	// goroutine uses PopFrontExcessFunc to process outboxes and shared channel
	// without registering for immediate delivery.
	//
	// Only one goroutine at a time can elect itself "spare" for scaling.
	combineQueue workq.Pending
	spareElected atomic.Bool

	combineOpMapMu sync.Mutex
	combineOpMap   map[combineOpID]any

	abandonedCombiners *activeCombinerMap

	// If there are tasks waiting to post work to combineQueue, the governor
	// will block new top-level scatters, thereby applying backpressure to
	// regulate the system.
	governor workq.Governor

	// Work that the pool has already committed to do because it was pulled from
	// combineQueue or generated by combiners
	workQueue workq.Accepted
}

// NewCombinerPool creates a new CombinerPool bound to the specified job.
//
// Panics if the job is nil or in the done state.
//
//nolint:contextcheck // background context used only for tracing
func NewCombinerPool(job *Job, options ...psgopt.CombinerPoolOption) *CombinerPool {
	traceRegion := "NewCombinerPool"
	defer trace.StartRegion(context.Background(), traceRegion).End()

	// Check if the job is done
	job.panicIfDone()

	cp := &CombinerPool{
		job: job,
	}

	trace.Logf(context.Background(), traceRegion,
		"CombinerPool=%p, job=%p, state=%p, combineQueue=%p, governor=%p, workQueue=%p",
		cp, job, &cp.state, &cp.combineQueue, &cp.governor, &cp.workQueue)

	cp.combineQueue.Init()
	cp.governor.Init()
	cp.workQueue.Init()
	cp.state.Init()

	// Apply default configuration
	cp.state.SetOptions(
		psgopt.WithConcurrencyBounds(0, -1), // unlimited by default
		psgopt.WithHighUtilizationThreshold(psgopt.DefaultCombinerPoolHighUtilizationThreshold),
		psgopt.WithMeasurementTimeConstant(psgopt.DefaultCombinerPoolMeasurementTimeConstant),
		psgopt.WithHistoryRetentionPeriod(psgopt.DefaultCombinerPoolHistoryRetentionPeriod),
		psgopt.WithMinThroughputROI(psgopt.DefaultCombinerPoolMinThroughputROI),
		psgopt.WithGrowthFactors(
			psgopt.DefaultCombinerPoolAggressiveGrowthFactor,
			psgopt.DefaultCombinerPoolConservativeGrowthFactor,
		),
		psgopt.WithIdleTimeout(psgopt.DefaultCombinerPoolIdleTimeout),
	)

	// Apply user options
	cp.state.SetOptions(options...)

	return cp
}

// checkInitialized panics if the CombinerPool was not properly initialized via NewCombinerPool
func (cp *CombinerPool) checkInitialized() {
	if cp.job == nil {
		panic("CombinerPool not initialized: must use NewCombinerPool")
	}
}

// combineOutboxKey returns a unique identifier for this CombinerPool for combine outbox mapping.
func (cp *CombinerPool) combineOutboxKey() outboxKey[workq.Work] {
	return cp
}

// SetOptions applies the given configuration options to the pool.
func (cp *CombinerPool) SetOptions(options ...psgopt.CombinerPoolOption) {
	cp.checkInitialized()
	cp.state.SetOptions(options...)
}

//nolint:contextcheck // goroutine will use job context
func (cp *CombinerPool) spawnNewGoroutine() {
	traceRegion := "CombinerPool.spawnNewGoroutine"
	trace.Logf(context.Background(), traceRegion,
		"CombinerPool=%p starting new goroutine", cp)
	wg := &cp.job.wg
	wg.Add(1)
	go func() {
		defer wg.Done()
		cp.goroutine()
	}()
}

func (cp *CombinerPool) goroutine() {
	var doneWg sync.WaitGroup
	doneCh := make(chan struct{})
	var doneErr error
	worker := &cpWorker{
		cp:     cp,
		doneCh: doneCh,
		doneErr: func() error {
			return doneErr
		},
		activeCombiners: &activeCombinerMap{},
	}

	traceRegion := "CombinerPool.goroutine"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "CombinerPool=%p, worker=%p", cp, worker)

	j := cp.job

	// Create the base goroutine context
	ctx, cancel := context.WithCancel(j.ctx)
	ctx, _ = j.ensureCtxMeta(ctx,
		func(ctx context.Context, meta *ctxMeta) context.Context {
			meta.ctxType = combineContext
			meta.executionEnvironment = worker
			return ctx
		},
	)

	defer func() {
		trace.Logf(context.Background(), traceRegion, "canceling context")
		cancel()
		doneWg.Wait()
	}()

	// Minimize the number of channels on which this goroutine must repeatedly
	// retrieve and select to reduce contention.
	doneWg.Add(1)
	go func() {
		defer doneWg.Done()
		select {
		case <-j.state.Done():
			doneErr = ErrJobDone
		case <-ctx.Done():
			doneErr = ctx.Err()
		}
		close(doneCh)
	}()

	// Create the dedicated outbox for this combiner goroutine to emit gathers to the job
	worker.emitOutbox = OutboxFor[workq.Work](&worker.outboxMap, j.gatherOutboxKey())

	trace.Logf(ctx, traceRegion, "cpWorker=%p, combinerMap=%p, emitOutbox=%p",
		worker, &worker.activeCombiners, worker.emitOutbox)

	// This executes after the deferred call to cp.state.GoroutineExited() so
	// that cp.state.LiveGoroutineCount() will have been updated before this
	// deferred function executes and a new spare goroutine is elected.
	defer func() {
		if worker.idleTimer != nil {
			timerp.Put(worker.idleTimer)
			// If the idle timer is set, we are the spare goroutine
			cp.spareElected.Store(false)
		}
	}()

	cp.state.GoroutineStarted()
	defer cp.state.GoroutineExited()

	addWorkFn := worker.AddWork

	for {
		if worker.idleTimer == nil {
			if cp.spareElected.CompareAndSwap(false, true) {
				worker.idleTimer = timerp.Get()
				worker.idleFollowupFn = worker.idleFollowup // avoid reallocation of closure

				abandonedCombiners := cp.abandonedCombiners
				cp.abandonedCombiners = nil
				if abandonedCombiners != nil {
					worker.activeCombiners.Merge(abandonedCombiners)
					worker.activeCombiners.FlushExcess(ctx, worker.emitOutbox, cp.state.LiveGoroutineCount())
				}
			}
		}

		err := cp.workQueue.ExecuteOne(ctx, addWorkFn)
		switch {
		case err == nil:
		case errors.Is(err, workq.ErrEndOfWork):
			// End of work for this (spare) goroutine
			if worker.idleTimer == nil {
				panic("end of work received for non-spare goroutine")
			}
			if cp.state.LiveGoroutineCount() > 1 {
				trace.Logf(ctx, traceRegion, "spare goroutine exiting")
				// Stash active combiners for the next spare goroutine to pick up.
				if cp.abandonedCombiners != nil {
					panic("abandonedCombiners was not nil at end of spare goroutine")
				}
				cp.abandonedCombiners = worker.activeCombiners
				worker.activeCombiners = nil
				if worker.nextJobFlushCh != nil {
					worker.nextJobFlushCh = nil
					worker.unregisterAsJobFlusher()
				}
				return
			} else {
				trace.Logf(ctx, traceRegion, "last goroutine at end of work, flushing combiners")
				if !worker.flushAll(ctx) {
					trace.Logf(ctx, traceRegion, "last goroutine exiting")
					return
				}
				return
			}
		case errIn(err, ErrJobDone, context.Canceled, context.DeadlineExceeded):
			trace.Logf(ctx, traceRegion, "exiting with err=%v", err)
			return
		default:
			panic(fmt.Sprintf("combiner goroutine received unexpected error: %v", err))
		}
	}
}

type combinePostWork struct {
	jobWork
	pool *CombinerPool
	work boundCombineWork
}

func (w *combinePostWork) Init(group workq.GroupID, pool *CombinerPool, work boundCombineWork) {
	w.jobWork.Init(group, pool.job)
	w.pool = pool
	w.work = work
}

func (w *combinePostWork) Execute(ctx context.Context, ex workq.Execution) error {
	traceRegion := "combinePostWork.Execute"
	defer trace.StartRegion(ctx, traceRegion).End()
	trace.Logf(ctx, traceRegion, "%v", w)

	if w.pool.state.MaybeSpawnGoroutine() {
		w.pool.spawnNewGoroutine()
	}

	posted, err := func() (bool, error) {
		// Discover outbox from execution environment
		ctx, meta := w.pool.job.ctxMeta(ctx)

		outbox := meta.LockOutbox(w.pool.combineOutboxKey())
		defer meta.UnlockOutbox()

		tryPost := func() bool {
			// Try non-blocking post - can be retried if it fails
			return w.pool.combineQueue.TryPushBack(outbox, w.work)
		}

		for {
			if tryPost() {
				return true, nil
			}

			if !ex.ShouldBlockOrListen() {
				return false, nil
			}

			if meta.MayQueue() != nil {
				// We expect to be queued and called again, so listen and don't block
				ex.AddToListeners(outbox.Listeners())
				// AddToListeners to be notified when spawning conditions change
				ex.AddToListeners(&w.pool.state.SpawnNotifier().Listeners)

				// Check again after registering for notification, but return
				// and expect to be called again if needed
				posted := tryPost()
				if !posted {
					// Call Waiting on the nested combineWork to notify the governor
					w.work.Waiting(&w.pool.governor)
				}
				return posted, nil
			}

			// No queuing support (task worker context) - use blocking post
			posted := true
			var err error
			w.pool.combineQueue.PushBackFunc(outbox, w.work, func(outbox *rdvq.Outbox[workq.Work]) {
				posted = false

				// Call Waiting on the nested combineWork to notify the governor
				w.work.Waiting(&w.pool.governor)

				// Slow path, really going to block now
				ex.Blocking()

				// Check if we should spawn another goroutine
				if w.pool.state.ShouldSpawnGoroutine() {
					w.pool.spawnNewGoroutine()
				}

				outboxCh := outbox.Ch()
				trace.Logf(ctx, traceRegion, "entering select: outbox=%p, outboxCh=%p", outbox, outboxCh)
				select {
				case outboxCh <- w.work:
					outbox.Filled()
					posted = true
					trace.Logf(ctx, traceRegion, "delivered value into outbox=%p, outboxCh=%p", outbox, outboxCh)
				case <-spawnWaitCh:
				case <-ctx.Done():
					trace.Logf(ctx, traceRegion, "received context done signal")
					err = ctx.Err()
				}
			})
		}
	}()

	if posted {
		ex.Starting() // Signal success only if we actually posted
		w.work = nil  // Clear the work reference since it's now owned by the queue
	}
	return err
}

//nolint:contextcheck // background context used only for tracing
func (w *combinePostWork) Free() {
	traceRegion := "combinePostWork.Free"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "%v", w)

	// Free the nested work item if we still own it
	if w.work != nil {
		trace.Logf(context.Background(), traceRegion, "freeing w.work")
		w.work.Free()
		w.work = nil
	}

	w.Close(w.pool.job)
	combinePostWorkPool.Put(w)
}

var combinePostWorkPool = omnipool.For[combinePostWork]()

//nolint:contextcheck // background context used only for tracing
func (cp *CombinerPool) newCombinePostWork(group workq.GroupID, bc boundCombineWork) *combinePostWork {
	traceRegion := "CombinerPool.newCombinePostWork"

	w := combinePostWorkPool.Get()
	w.Init(group, cp, bc)

	trace.Logf(context.Background(), traceRegion, "CombinerPool=%p created %v", cp, w)
	return w
}

func (cp *CombinerPool) postCombineNowOrQueue(
	ctx context.Context,
	meta *ctxMeta,
	deadline time.Time,
	postWork *combinePostWork,
	queueFn workq.QueueWorkFunc,
) (startedOrQueued bool, err error) {
	traceRegion := "postCombineNowOrQueue"
	defer trace.StartRegion(ctx, traceRegion).End()

	executor := executorPool.Get()
	defer executorPool.Put(executor)
	ex := executor.BaseEx()

	queued := false
	defer func() {
		if ex.Started() || !queued {
			postWork.Free()
		}

		startedOrQueued = ex.Started() || queued
		if err == nil {
			trace.Logf(ctx, traceRegion, "returning startedOrQueued=%v", startedOrQueued)
		} else {
			trace.Logf(ctx, traceRegion, "returning startedOrQueued=%v, err=%v", startedOrQueued, err)
		}
	}()

	if false && meta.IsTopLevel() {
		// Apply backpressure at top level by processing some outstanding work first
		err := cp.job.yield(ctx, deadline)
		if err != nil {
			return false, err
		}

		// Signal the work that it should block by making AddToListeners non-nil
		ex.AddToListeners = func(*workq.Listeners) {
			panic("unexpected call to postCombineNowOrQueue.ex.AddToListeners")
		}
	}

	if deadline.IsZero() || time.Now().Before(deadline) {
		err = postWork.Execute(ctx, ex)
	}

	if err == nil && !ex.Started() && queueFn != nil {
		queued = true
		queueFn(postWork)
	}

	return
}
