// Code generated by "stringer -type=contextType -linecomment"; DO NOT EDIT.

package psg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[topLevelContext-0]
	_ = x[taskContext-1]
	_ = x[skimContext-2]
	_ = x[combineContext-3]
}

const _contextType_name = "top-leveltaskskimcombine"

var _contextType_index = [...]uint8{0, 9, 13, 17, 24}

func (i contextType) String() string {
	if i < 0 || i >= contextType(len(_contextType_index)-1) {
		return "contextType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _contextType_name[_contextType_index[i]:_contextType_index[i+1]]
}
