// Copyright (c) Peter Newcomb. All rights reserved.
// Licensed under the MIT License.

package psg

import (
	"context"
	"fmt"
	"sync"

	"github.com/petenewcomb/psg-go/internal/trace"

	"github.com/petenewcomb/psg-go/internal/omnipool"
	"github.com/petenewcomb/psg-go/internal/workq"
	"github.com/petenewcomb/psg-go/psgopt"
)

// FunnelPool manages a pool of goroutines that execute funnels.
// It handles concurrency limits, spawning new goroutines, and reusing existing ones.
type FunnelPool struct {
	job *Pool

	funnelQueue workq.Pending

	// Pending flushes live on workQueue as scheduled work: a
	// funnelInstance with a future deadline is workQueue.Schedule'd and,
	// once due, surfaces as fresh work whose Execute runs the flush. Any
	// worker drives it; the per-instance mu makes parallel Flush safe.

	// Work that the pool has already committed to do because it was pulled from
	// funnelQueue or generated by funnels
	workQueue workq.Accepted

	// flusherDone is closed when the persistent flush driver goroutine returns.
	// The flusher is deliberately NOT tracked by Pool.wg (that joins worker
	// goroutines, which now live on the global defaultPool). Funnel-flush
	// completion is governed by jobstate reference counts — CloseAndSkimAll/SkimAll
	// block on state.Done until every funnelInstance has flushed — so a wave's
	// drain already waits for the flush work itself. This channel only lets
	// Wave.CancelAndWait join the goroutine, closing the exit window before
	// teardown returns.
	flusherDone chan struct{}
}

// newFunnelPool creates the job's internal funnel engine. Not user-facing: funnels
// are created with NewFunnel(wave, ...), which calls Pool.funnelPool to lazily
// build and share one of these per job.
//
//nolint:contextcheck // background context used only for tracing
func newFunnelPool(job *Pool) *FunnelPool {
	traceRegion := "newFunnelPool"
	defer trace.StartRegion(context.Background(), traceRegion).End()

	// Check if the job is done
	job.panicIfDone()

	cp := &FunnelPool{
		job:         job,
		flusherDone: make(chan struct{}),
	}

	trace.Logf(context.Background(), traceRegion,
		"FunnelPool=%p, job=%p, funnelQueue=%p, workQueue=%p",
		cp, job, &cp.funnelQueue, &cp.workQueue)

	cp.funnelQueue.Init()
	// workQueue holds only scheduled funnelInstance flushes (funnel BODY work runs
	// on the global pool via defaultPool.Post). One persistent flusher drives it.
	cp.workQueue.Init(nil)

	// Run the single persistent flush driver (drains deadline-driven +
	// end-of-work funnelInstance flushes until the job reaches Done).
	cp.spawnFlusher()

	return cp
}

// checkInitialized panics if the FunnelPool was not properly initialized via NewFunnelPool
func (cp *FunnelPool) checkInitialized() {
	if cp.job == nil {
		panic("FunnelPool not initialized: must use NewFunnelPool")
	}
}

// SetOptions is retained for source compatibility but is now a no-op: the funnel
// body runs on the uncapped global worker.Pool and there is a single persistent
// flush driver, so there are no per-pool concurrency/idle dials left to set.
func (cp *FunnelPool) SetOptions(_ ...psgopt.FunnelPoolOption) {
	cp.checkInitialized()
}

// spawnFlusher starts the single persistent flush driver goroutine. It is tracked
// by the job's wait group so the job's teardown joins it.
//
//nolint:contextcheck // goroutine will use job context
func (cp *FunnelPool) spawnFlusher() {
	traceRegion := "FunnelPool.spawnFlusher"
	trace.Logf(context.Background(), traceRegion,
		"FunnelPool=%p starting flush driver", cp)
	go func() {
		defer close(cp.flusherDone)
		cp.flusher()
	}()
}

// joinFlusher blocks until the flush driver goroutine has fully exited. The
// caller is expected to have already driven the flusher toward exit — either a
// graceful drain reaching job Done, or pool-context cancellation — so this only
// closes the goroutine-exit window before a wave's teardown returns.
func (cp *FunnelPool) joinFlusher() {
	<-cp.flusherDone
}

func (cp *FunnelPool) flusher() {
	var doneWg sync.WaitGroup
	doneCh := make(chan struct{})
	var doneErr error
	worker := &cpWorker{
		cp:     cp,
		doneCh: doneCh,
		doneErr: func() error {
			return doneErr
		},
	}
	defer worker.Release()

	traceRegion := "FunnelPool.goroutine"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "FunnelPool=%p, worker=%p", cp, worker)

	j := cp.job

	// Create the base goroutine context
	ctx, cancel := context.WithCancel(j.ctx)
	ctx, _ = j.ensureCtxMeta(ctx,
		func(ctx context.Context, meta *ctxMeta) context.Context {
			meta.ctxType = funnelContext
			meta.executionEnvironment = worker
			// Worker contexts are fresh permit-roots: for a subjob, j.ctx
			// carries the dispatching body's meta from a foreign pool, and
			// inheriting the parent link would let this worker find that
			// body's held limiter permit across the goroutine boundary.
			meta.parent = nil
			return ctx
		},
	)

	defer func() {
		trace.Logf(context.Background(), traceRegion, "canceling context")
		cancel()
		doneWg.Wait()
	}()

	// Minimize the number of channels on which this goroutine must repeatedly
	// retrieve and select to reduce contention.
	doneWg.Add(1)
	go func() {
		defer doneWg.Done()
		select {
		case <-j.state.Done():
			doneErr = ErrJobDone
		case <-ctx.Done():
			doneErr = ctx.Err()
		}
		close(doneCh)
	}()

	trace.Logf(ctx, traceRegion, "cpWorker=%p", worker)

	// Subscribe to the job's end-of-work flush signal up front. Legacy did this
	// lazily in executeFunnel (when the cpWorker ran a funnel body), but the body
	// now runs on the global pool, so this persistent flusher must subscribe at
	// startup or it would never wake to run the end-of-work flush sweep.
	worker.nextJobFlushCh = j.state.FlushChan()

	addWorkFn := worker.AddWork

	// Persistent flush driver: drain due scheduled funnelInstance flushes
	// (deadline-driven) and run the end-of-work flush sweep when the job's
	// FlushChan fires (popSelect installs flushAll as the followup), looping until
	// the job reaches Done / is cancelled. There is exactly one flusher per pool
	// (no idle-exit, no spawn coordination), so the legacy multi-worker
	// ErrEndOfWork / GoroutineExiting dance is gone.
	for {
		err := cp.workQueue.ExecuteOne(ctx, addWorkFn)
		switch {
		case err == nil:
			// Ran a due flush (or the end-of-work flushAll followup); keep going.
		case errIn(err, ErrJobDone, context.Canceled, context.DeadlineExceeded):
			trace.Logf(ctx, traceRegion, "flusher exiting with err=%v", err)
			return
		default:
			panic(fmt.Sprintf("funnel flusher received unexpected error: %v", err))
		}
	}
}

type funnelPostWork struct {
	poolWork
	pool *FunnelPool
	work boundFunnelWork
}

func (w *funnelPostWork) Init(group workq.GroupID, pool *FunnelPool, work boundFunnelWork) {
	w.poolWork.Init(group, pool.job)
	w.pool = pool
	w.work = work
}

func (w *funnelPostWork) Execute(ctx context.Context, ex workq.Execution) error {
	traceRegion := "funnelPostWork.Execute"
	defer trace.StartRegion(ctx, traceRegion).End()
	trace.Logf(ctx, traceRegion, "%v", w)

	// Handoff to the GLOBAL pool's shared work queue (mirrors taskPostWork). The
	// unified Queue.Post replaces the legacy funnelQueue try/listen/block loop, and
	// the pool's unmet-demand signal replaces the cpstate spawn machinery
	// (ShouldSpawn*/SpawnNotifier/spawnNewGoroutine — all dropped, DECISION C). The
	// governor still applies: onWait registers the funnel work's downstream
	// saturation on the job's governor — the SAME one top-level task admission gates
	// on (launcherScatterWork) and skim registers on — so funnel backpressure is now
	// unified with the rest of the wave's sources rather than landing on a separate,
	// never-consulted funnel governor. (The field's physical Pool→Wave move rides
	// with the skim seam; today the 1:1 Pool↔Wave binding makes it the per-wave
	// governor.)
	// shouldBlock is read directly from the ctx (not via j.ctxMeta, which panics on
	// a missing meta): a producer only postpones onto the global queue in LISTEN
	// mode (shouldBlock=false), and a global worker re-running it has no ctxMeta.
	meta, _ := ctx.Value(ctxMetaValueKey{}).(*ctxMeta)
	shouldBlock := meta != nil && meta.job == w.pool.job && meta.ShouldBlock()
	onWait := func() { w.work.Waiting(&w.pool.job.governor) }
	posted, err := defaultPool.Post(ctx, ex, shouldBlock, w.work, onWait)
	if posted {
		w.work = nil // ownership transferred to the queue
	}
	return err
}

//nolint:contextcheck // background context used only for tracing
func (w *funnelPostWork) Free() {
	traceRegion := "funnelPostWork.Free"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "%v", w)

	// Free the nested work item if we still own it
	if w.work != nil {
		trace.Logf(context.Background(), traceRegion, "w.work.Free()")
		w.work.Free()
		w.work = nil
	}

	w.Close(w.pool.job)
	funnelPostWorkPool.Put(w)
}

var funnelPostWorkPool = omnipool.For[funnelPostWork]()

//nolint:contextcheck // background context used only for tracing
func (cp *FunnelPool) newFunnelPostWork(group workq.GroupID, bc boundFunnelWork) *funnelPostWork {
	traceRegion := "FunnelPool.newFunnelPostWork"

	w := funnelPostWorkPool.Get()
	w.Init(group, cp, bc)

	trace.Logf(context.Background(), traceRegion, "FunnelPool=%p created %v", cp, w)
	return w
}
