// Copyright (c) Peter Newcomb. All rights reserved.
// Licensed under the MIT License.

package streampool

import (
	"context"
	"fmt"
	"sync"

	"github.com/petenewcomb/streampool/internal/trace"

	"github.com/petenewcomb/streampool/internal/omnipool"
	"github.com/petenewcomb/streampool/internal/workq"
)

// funnelEngine is a Wave's lazily-created funnel machinery: the scheduled-flush
// queue plus the single persistent goroutine that drives deadline-driven and
// end-of-work flushes. Funnel BODY work runs on the global defaultPool (not here);
// this type only owns flush scheduling and the flusher. One per Wave, built on the
// first NewFunnel(wave, …).
type funnelEngine struct {
	job *Wave

	funnelQueue workq.Pending

	// Pending flushes live on workQueue as scheduled work: a
	// funnelInstance with a future deadline is workQueue.Schedule'd and,
	// once due, surfaces as fresh work whose Execute runs the flush. Any
	// worker drives it; the per-instance mu makes parallel Flush safe.

	// Work that the pool has already committed to do because it was pulled from
	// funnelQueue or generated by funnels
	workQueue workq.Accepted

	// funnels is the registry of funnels created on this wave (heterogeneous T via
	// the funnelFinalizer interface). NewFunnel registers; the end-of-work flush
	// sweep (cpWorker.flushAll) drains and finalizes them. Registration happens
	// during the wave's Open phase and finalization at Flushing (Open < Flushing),
	// but a mutex guards concurrent NewFunnel on one wave.
	funnelsMu sync.Mutex
	funnels   []funnelFinalizer

	// flusherDone is closed when the persistent flush driver goroutine returns.
	// The flusher is deliberately NOT tracked by Wave.wg (that joins worker
	// goroutines, which now live on the global defaultPool). Funnel-flush
	// completion is governed by wavestate reference counts — CloseAndSkimAll/SkimAll
	// block on state.Done until every funnelInstance has flushed — so a wave's
	// drain already waits for the flush work itself. This channel lets
	// Wave.ensureArmed join the prior cycle's flusher before re-arming a reused
	// (e.g. pooled) wave, ensuring the old goroutine has exited before the
	// WaveState it reads is re-Init'd.
	flusherDone chan struct{}
}

// newFunnelEngine creates a wave's internal funnel engine. Not user-facing: funnels
// are created with NewFunnel(wave, ...), which calls Wave.funnelEngine to lazily
// build and share one of these per wave.
//
//nolint:contextcheck // background context used only for tracing
func newFunnelEngine(job *Wave) *funnelEngine {
	traceRegion := "newFunnelEngine"
	defer trace.StartRegion(context.Background(), traceRegion).End()

	// Check if the job is done
	job.panicIfDone()

	fe := &funnelEngine{
		job:         job,
		flusherDone: make(chan struct{}),
	}

	trace.Logf(context.Background(), traceRegion,
		"funnelEngine=%p, job=%p, funnelQueue=%p, workQueue=%p",
		fe, job, &fe.funnelQueue, &fe.workQueue)

	fe.funnelQueue.Init()
	// workQueue holds only scheduled funnelInstance flushes (funnel BODY work runs
	// on the global pool via defaultPool.Post). One persistent flusher drives it.
	fe.workQueue.Init(nil)

	// Capture the end-of-work flush channel HERE, synchronously, before
	// spawning the flusher goroutine. newFunnelEngine always runs during the
	// wave's Open phase (funnels are created before CloseAndSkimAll), strictly
	// before any Closed→Flushing rotation, so this is the pre-rotation channel
	// that noMoreWork closes at the first Flushing transition. If we instead
	// read FlushChan() inside the flusher goroutine, an arbitrarily-delayed
	// goroutine could read the POST-rotation channel and park on it forever,
	// missing the wave's one end-of-work flush signal (the funnel-instance
	// reference-leak hang; see WORKING_NOTES.md).
	flushCh := job.state.FlushChan()

	// Run the single persistent flush driver (drains deadline-driven +
	// end-of-work funnelInstance flushes until the job reaches Done).
	fe.spawnFlusher(flushCh)

	return fe
}

// spawnFlusher starts the single persistent flush driver goroutine. flushCh is
// the end-of-work flush channel captured synchronously by the caller (before
// any Flushing rotation can occur); see newFunnelEngine.
//
//nolint:contextcheck // goroutine will use job context
func (fe *funnelEngine) spawnFlusher(flushCh <-chan struct{}) {
	traceRegion := "funnelEngine.spawnFlusher"
	trace.Logf(context.Background(), traceRegion,
		"funnelEngine=%p starting flush driver", fe)
	go func() {
		defer close(fe.flusherDone)
		fe.flusher(flushCh)
	}()
}

// registerFunnel adds a funnel to the engine's registry so the end-of-work flush
// sweep finalizes it. Called from NewFunnel during the wave's Open phase.
func (fe *funnelEngine) registerFunnel(f funnelFinalizer) {
	fe.funnelsMu.Lock()
	fe.funnels = append(fe.funnels, f)
	fe.funnelsMu.Unlock()
}

// finalizeFunnels finalizes every registered funnel (factory.Close + recycle +
// drop each funnel's per-wave reference). Called once from the end-of-work flush
// sweep, AFTER all instances have been force-flushed. Idempotent: it takes the slice
// under the lock and leaves the registry empty, so a second sweep finalizes nothing.
func (fe *funnelEngine) finalizeFunnels(ctx context.Context) {
	fe.funnelsMu.Lock()
	funnels := fe.funnels
	fe.funnels = nil
	fe.funnelsMu.Unlock()
	for _, f := range funnels {
		f.finalize(ctx)
	}
}

// joinFlusher blocks until the flush driver goroutine has fully exited. The
// caller is expected to have already driven the flusher toward exit — either a
// graceful drain reaching job Done, or pool-context cancellation — so this only
// closes the goroutine-exit window before a wave's teardown returns.
func (fe *funnelEngine) joinFlusher() {
	<-fe.flusherDone
}

func (fe *funnelEngine) flusher(flushCh <-chan struct{}) {
	var doneWg sync.WaitGroup
	doneCh := make(chan struct{})
	var doneErr error
	worker := &cpWorker{
		fEngine: fe,
		doneCh:  doneCh,
		doneErr: func() error {
			return doneErr
		},
	}
	defer worker.Release()

	traceRegion := "funnelEngine.goroutine"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "funnelEngine=%p, worker=%p", fe, worker)

	j := fe.job

	// Create the base goroutine context. The Wave owns no context, so this roots at
	// Background: the flusher's lifetime is governed by the wave reaching Done (the
	// done-watcher below selects state.Done()), not by a wave-owned cancel. cancel
	// only tears down this goroutine's own derived ctx on exit.
	ctx, cancel := context.WithCancel(context.Background())
	ctx, _ = j.ensureCtxMeta(ctx,
		func(ctx context.Context, meta *ctxMeta) context.Context {
			meta.ctxType = funnelContext
			meta.executionEnvironment = worker
			// The flusher belongs to wave j: stamp it as the ambient wave so a
			// flush body can dispatch nil-wave ops (op.Submit) the same way an
			// accumulate body can. The flusher ctx roots at Background (the wave
			// owns no ctx), so ensureCtxMeta has no source to copy this from.
			meta.wave = j
			// Worker contexts are fresh permit-roots: inheriting a parent link
			// would let this worker find a dispatching body's held limiter permit
			// across the goroutine boundary, so sever it.
			meta.parent = nil
			return ctx
		},
	)

	defer func() {
		trace.Logf(context.Background(), traceRegion, "canceling context")
		cancel()
		doneWg.Wait()
	}()

	// Minimize the number of channels on which this goroutine must repeatedly
	// retrieve and select to reduce contention.
	doneWg.Add(1)
	go func() {
		defer doneWg.Done()
		select {
		case <-j.state.Done():
			doneErr = ErrWaveDone
		case <-ctx.Done():
			doneErr = ctx.Err()
		}
		close(doneCh)
	}()

	trace.Logf(ctx, traceRegion, "cpWorker=%p", worker)

	// Subscribe to the job's end-of-work flush signal. The channel was captured
	// synchronously at engine creation (newFunnelEngine), before any Flushing
	// rotation could occur — NOT read here, because this goroutine may be
	// scheduled arbitrarily late and would otherwise read the post-rotation
	// channel and miss the wave's end-of-work flush signal forever (the
	// funnel-instance reference-leak hang). Legacy subscribed lazily in
	// executeFunnel (when the cpWorker ran a funnel body), but the body now runs
	// on the global pool, so this persistent flusher must subscribe up front or
	// it would never wake to run the end-of-work flush sweep.
	worker.nextJobFlushCh = flushCh

	addWorkFn := worker.AddWork

	// Persistent flush driver: drain due scheduled funnelInstance flushes
	// (deadline-driven) and run the end-of-work flush sweep when the job's
	// FlushChan fires (popSelect installs flushAll as the followup), looping until
	// the job reaches Done / is cancelled. There is exactly one flusher per pool
	// (no idle-exit, no spawn coordination), so the legacy multi-worker
	// ErrEndOfWork / GoroutineExiting dance is gone.
	for {
		err := fe.workQueue.ExecuteOne(ctx, addWorkFn, nil)
		switch {
		case err == nil:
			// Ran a due flush (or the end-of-work flushAll followup); keep going.
		case errIn(err, ErrWaveDone, context.Canceled, context.DeadlineExceeded):
			trace.Logf(ctx, traceRegion, "flusher exiting with err=%v", err)
			return
		default:
			panic(fmt.Sprintf("funnel flusher received unexpected error: %v", err))
		}
	}
}

type funnelPostWork struct {
	poolWork
	fEngine *funnelEngine
	work    boundFunnelWork
}

func (w *funnelPostWork) Init(group workq.GroupID, fe *funnelEngine, work boundFunnelWork) {
	w.poolWork.Init(group, fe.job)
	w.fEngine = fe
	w.work = work
}

func (w *funnelPostWork) Execute(ctx context.Context, ex workq.Execution) error {
	traceRegion := "funnelPostWork.Execute"
	defer trace.StartRegion(ctx, traceRegion).End()
	trace.Logf(ctx, traceRegion, "%v", w)

	// Handoff to the GLOBAL pool's shared work queue (mirrors taskPostWork). The
	// unified Queue.Post replaces the legacy funnelQueue try/listen/block loop, and
	// the pool's unmet-demand signal replaces the cpstate spawn machinery
	// (ShouldSpawn*/SpawnNotifier/spawnNewGoroutine — all dropped, DECISION C). The
	// governor still applies: onWait registers the funnel work's downstream
	// saturation on the job's governor — the SAME one top-level task admission gates
	// on (launcherScatterWork) and skim registers on — so funnel backpressure is now
	// unified with the rest of the wave's sources rather than landing on a separate,
	// never-consulted funnel governor.
	// shouldBlock is read directly from the ctx (not via j.ctxMeta, which panics on
	// a missing meta): a producer only postpones onto the global queue in LISTEN
	// mode (shouldBlock=false), and a global worker re-running it has no ctxMeta.
	meta, _ := metaFromContext(ctx)
	shouldBlock := meta != nil && meta.job == w.fEngine.job && meta.ShouldBlock()
	onWait := func() { w.work.Waiting(&w.fEngine.job.governor) }
	posted, err := defaultPool.Post(ctx, ex, shouldBlock, w.work, onWait)
	if posted {
		w.work = nil // ownership transferred to the queue
	}
	return err
}

//nolint:contextcheck // background context used only for tracing
func (w *funnelPostWork) Free() {
	traceRegion := "funnelPostWork.Free"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "%v", w)

	// Free the nested work item if we still own it
	if w.work != nil {
		trace.Logf(context.Background(), traceRegion, "w.work.Free()")
		w.work.Free()
		w.work = nil
	}

	w.Close(w.fEngine.job)
	funnelPostWorkPool.Put(w)
}

var funnelPostWorkPool = omnipool.For[funnelPostWork]()

//nolint:contextcheck // background context used only for tracing
func (fe *funnelEngine) newFunnelPostWork(group workq.GroupID, bc boundFunnelWork) *funnelPostWork {
	traceRegion := "funnelEngine.newFunnelPostWork"

	w := funnelPostWorkPool.Get()
	w.Init(group, fe, bc)

	trace.Logf(context.Background(), traceRegion, "funnelEngine=%p created %v", fe, w)
	return w
}
