// Copyright (c) Peter Newcomb. All rights reserved.
// Licensed under the MIT License.

package psg

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/petenewcomb/psg-go/internal/jobstate"
	"github.com/petenewcomb/psg-go/internal/rdvq"
	"github.com/petenewcomb/psg-go/internal/trace"

	"github.com/petenewcomb/psg-go/internal/cpstate"
	"github.com/petenewcomb/psg-go/internal/omnipool"
	"github.com/petenewcomb/psg-go/internal/timerp"
	"github.com/petenewcomb/psg-go/internal/workq"
	"github.com/petenewcomb/psg-go/psgopt"
)

// FunnelPool manages a pool of goroutines that execute funnels.
// It handles concurrency limits, spawning new goroutines, and reusing existing ones.
type FunnelPool struct {
	job *Pool

	// FunnelPoolState hosts the data and core logic for managing the pool of
	// goroutines to maximize throughput with the minimum number of goroutines
	// and therefore duplication of individual funnels.
	state    cpstate.FunnelPoolState
	inFlight jobstate.InFlightCounter

	funnelQueue workq.Pending

	// Pending flushes live on workQueue as scheduled work: a
	// funnelInstance with a future deadline is workQueue.Schedule'd and,
	// once due, surfaces as fresh work whose Execute runs the flush. Any
	// worker drives it; the per-instance mu makes parallel Flush safe.

	// If there are tasks waiting to post work to funnelQueue, the governor
	// will block new top-level scatters, thereby applying backpressure to
	// regulate the system.
	governor workq.Governor

	// Work that the pool has already committed to do because it was pulled from
	// funnelQueue or generated by funnels
	workQueue workq.Accepted

	unmetDemandFn workq.RenotifyFunc // avoid closure reallocation
}

// NewFunnelPool creates a new FunnelPool bound to the specified job.
//
// Panics if the job is nil or in the done state.
//
//nolint:contextcheck // background context used only for tracing
func NewFunnelPool(job *Pool, options ...psgopt.FunnelPoolOption) *FunnelPool {
	traceRegion := "NewFunnelPool"
	defer trace.StartRegion(context.Background(), traceRegion).End()

	// Check if the job is done
	job.panicIfDone()

	cp := &FunnelPool{
		job: job,
	}

	cp.unmetDemandFn = func() { cp.spawnNewGoroutine() }

	trace.Logf(context.Background(), traceRegion,
		"FunnelPool=%p, job=%p, state=%p, funnelQueue=%p, governor=%p, workQueue=%p",
		cp, job, &cp.state, &cp.funnelQueue, &cp.governor, &cp.workQueue)

	cp.funnelQueue.Init()
	cp.governor.Init()
	cp.workQueue.Init(cp.unmetDemandFn)
	cp.state.Init()

	// Apply default configuration
	cp.state.SetOptions(
		psgopt.WithMaxConcurrency(-1), // unlimited by default
		psgopt.WithIdleTimeout(psgopt.DefaultFunnelPoolIdleTimeout),
		psgopt.WithIdleJitter(psgopt.DefaultFunnelPoolIdleJitter),
	)

	// Apply user options
	cp.state.SetOptions(options...)

	return cp
}

// checkInitialized panics if the FunnelPool was not properly initialized via NewFunnelPool
func (cp *FunnelPool) checkInitialized() {
	if cp.job == nil {
		panic("FunnelPool not initialized: must use NewFunnelPool")
	}
}

// SetOptions applies the given configuration options to the pool.
func (cp *FunnelPool) SetOptions(options ...psgopt.FunnelPoolOption) {
	cp.checkInitialized()
	cp.state.SetOptions(options...)
}

//nolint:contextcheck // goroutine will use job context
func (cp *FunnelPool) spawnNewGoroutine() {
	traceRegion := "FunnelPool.spawnNewGoroutine"
	trace.Logf(context.Background(), traceRegion,
		"FunnelPool=%p starting new goroutine", cp)
	wg := &cp.job.wg
	wg.Add(1)
	go func() {
		defer wg.Done()
		cp.goroutine()
	}()
}

func (cp *FunnelPool) goroutine() {
	var doneWg sync.WaitGroup
	doneCh := make(chan struct{})
	var doneErr error
	worker := &cpWorker{
		cp:     cp,
		doneCh: doneCh,
		doneErr: func() error {
			return doneErr
		},
	}
	defer worker.Release()

	traceRegion := "FunnelPool.goroutine"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "FunnelPool=%p, worker=%p", cp, worker)

	j := cp.job

	// Create the base goroutine context
	ctx, cancel := context.WithCancel(j.ctx)
	ctx, _ = j.ensureCtxMeta(ctx,
		func(ctx context.Context, meta *ctxMeta) context.Context {
			meta.ctxType = funnelContext
			meta.executionEnvironment = worker
			// Worker contexts are fresh permit-roots: for a subjob, j.ctx
			// carries the dispatching body's meta from a foreign pool, and
			// inheriting the parent link would let this worker find that
			// body's held limiter permit across the goroutine boundary.
			meta.parent = nil
			return ctx
		},
	)

	defer func() {
		trace.Logf(context.Background(), traceRegion, "canceling context")
		cancel()
		doneWg.Wait()
	}()

	// Minimize the number of channels on which this goroutine must repeatedly
	// retrieve and select to reduce contention.
	doneWg.Add(1)
	go func() {
		defer doneWg.Done()
		select {
		case <-j.state.Done():
			doneErr = ErrJobDone
		case <-ctx.Done():
			doneErr = ctx.Err()
		}
		close(doneCh)
	}()

	trace.Logf(ctx, traceRegion, "cpWorker=%p", worker)

	worker.idleTimer = timerp.Get()
	defer timerp.Put(worker.idleTimer)

	cp.state.GoroutineStarted()

	addWorkFn := worker.AddWork

	confirmEndOfWork := false
	for {
		confirmingEndOfWork := confirmEndOfWork
		confirmEndOfWork = false

		err := cp.workQueue.ExecuteOne(ctx, addWorkFn)
		switch {
		case err == nil:
		case errors.Is(err, workq.ErrEndOfWork):
			if confirmingEndOfWork {
				trace.Logf(ctx, traceRegion, "last goroutine at end of work, flushing funnels")
				// Flush every pending instance through the shared scheduled
				// queue. Any worker can do this (see flushAll); a worker that
				// never ran a funnel must still flush so live instances'
				// barrier references drop and the job can reach Done.
				worker.flushAll(ctx)
			}
			if cp.state.GoroutineExiting() {
				// This is the last goroutine running. Keep running a bit longer
				// to confirm that there's nothing more to do
				cp.state.GoroutineRestarted()
				confirmEndOfWork = cp.inFlight.IsZero()
			} else {
				trace.Logf(ctx, traceRegion, "goroutine exiting")
				// No timer-holder handoff needed: remaining workers each arm
				// their own deadline timer in workq's WaitForNew, and a flush
				// scheduled while they are parked wakes them via the scheduled-work
				// queue's wake hook.
				// The flush-signal subscription holds no reference, so
				// there is nothing to release on exit.
				worker.nextJobFlushCh = nil
				return
			}
		case errIn(err, ErrJobDone, context.Canceled, context.DeadlineExceeded):
			trace.Logf(ctx, traceRegion, "exiting with err=%v", err)
			// Do NOT call GoroutineExiting() here. The Pool is shutting down, so
			// goroutine accounting no longer matters. Additionally, this goroutine
			// may have already called GoroutineExiting() then GoroutineRestarted()
			// on the ErrEndOfWork path above, and calling it again would cause
			// double-decrement.
			return
		default:
			panic(fmt.Sprintf("funnel goroutine received unexpected error: %v", err))
		}
	}
}

type funnelPostWork struct {
	poolWork
	pool *FunnelPool
	work boundFunnelWork
}

func (w *funnelPostWork) Init(group workq.GroupID, pool *FunnelPool, work boundFunnelWork) {
	w.poolWork.Init(group, pool.job)
	w.pool = pool
	w.work = work
}

func (w *funnelPostWork) Execute(ctx context.Context, ex workq.Execution) error {
	traceRegion := "funnelPostWork.Execute"
	defer trace.StartRegion(ctx, traceRegion).End()
	trace.Logf(ctx, traceRegion, "%v", w)

	posted, err := func() (bool, error) {
		// Discover outbox from execution environment
		ctx, meta := w.pool.job.ctxMeta(ctx)

		spawnWaiters := &w.pool.state.SpawnNotifier().Waiters

		maybeSpawn := func() {
			if w.pool.state.ShouldSpawnGoroutine() {
				w.pool.spawnNewGoroutine()
			}
		}

		waiting := func() {
			// Call Waiting on the nested funnelWork to notify the governor
			w.work.Waiting(&w.pool.governor)

			maybeSpawn()
		}

		tryPost := func() bool {
			// Try non-blocking post - can be retried if it fails
			return w.pool.funnelQueue.TryPushBack(meta.Sender(), w.work, maybeSpawn)
		}

		for {
			if tryPost() {
				return true, nil
			}

			if !ex.ShouldBlockOrPostpone() {
				return false, nil
			}

			if !meta.ShouldBlock() {
				// We expect to be queued and called again, so listen and don't block
				ex.AddToListeners(w.pool.funnelQueue.ListenersFor(meta.Sender()))
				// AddToListeners to be notified when spawning conditions change
				ex.AddToListeners(&w.pool.state.SpawnNotifier().Listeners)

				// Check again after registering for notification, but return
				// and expect to be called again if needed
				posted := tryPost()
				if !posted {
					waiting()
				}
				trace.Logf(ctx, traceRegion, "meta.QueueFunc() != nil, posted=%v", posted)
				return posted, nil
			}

			posted := true
			var err error
			shouldWait := func() bool {
				return !tryPost()
			}
			spawnWaiters.WaitFunc(meta.Waiter(), shouldWait, func(spawnWaitCh <-chan rdvq.RenotifyFunc) rdvq.RenotifyFunc {
				var renotifyFn rdvq.RenotifyFunc
				w.pool.funnelQueue.PushBackFunc(meta.Sender(), w.work, maybeSpawn, func(outboxCh chan<- workq.Work) bool {
					// Slow path, posting no longer implicit
					posted = false

					// Really going to block now
					ex.Blocking()

					waiting()

					trace.Logf(ctx, traceRegion,
						"entering select: outboxCh=%p, spawnWaitCh=%p",
						outboxCh, spawnWaitCh)
					select {
					case outboxCh <- w.work:
						posted = true
						trace.Logf(ctx, traceRegion, "delivered value into outboxCh=%p", outboxCh)
						return true
					case rf := <-spawnWaitCh:
						renotifyFn = rf
						trace.Logf(ctx, traceRegion, "received signal from spawnWaitCh=%p", spawnWaitCh)
						if w.pool.state.ShouldSpawnGoroutine() {
							w.pool.spawnNewGoroutine()
						}
						return false
					case <-ctx.Done():
						trace.Logf(ctx, traceRegion, "received context done signal")
						err = ctx.Err()
						return false
					}
				})
				return renotifyFn
			})
			trace.Logf(ctx, traceRegion, "meta.ShouldBlock(), posted=%v, err=%v", posted, err)
			if posted || err != nil {
				return posted, err
			}
		}
	}()

	if posted {
		ex.Starting() // Signal success only if we actually posted
		w.work = nil  // Clear the work reference since it's now owned by the queue

		// Now that the work is in the queue, make sure there's a goroutine to
		// pick it up
		trace.Logf(ctx, traceRegion, "calling ShouldSpawnFirstGoroutine")
		if w.pool.state.ShouldSpawnFirstGoroutine() {
			trace.Logf(ctx, traceRegion, "spawning first goroutine")
			w.pool.spawnNewGoroutine()
		} else {
			trace.Logf(ctx, traceRegion, "no need to spawn first goroutine")
		}
	}
	return err
}

//nolint:contextcheck // background context used only for tracing
func (w *funnelPostWork) Free() {
	traceRegion := "funnelPostWork.Free"
	defer trace.StartRegion(context.Background(), traceRegion).End()
	trace.Logf(context.Background(), traceRegion, "%v", w)

	// Free the nested work item if we still own it
	if w.work != nil {
		trace.Logf(context.Background(), traceRegion, "w.work.Free()")
		w.work.Free()
		w.work = nil
	}

	w.Close(w.pool.job)
	funnelPostWorkPool.Put(w)
}

var funnelPostWorkPool = omnipool.For[funnelPostWork]()

//nolint:contextcheck // background context used only for tracing
func (cp *FunnelPool) newFunnelPostWork(group workq.GroupID, bc boundFunnelWork) *funnelPostWork {
	traceRegion := "FunnelPool.newFunnelPostWork"

	w := funnelPostWorkPool.Get()
	w.Init(group, cp, bc)

	trace.Logf(context.Background(), traceRegion, "FunnelPool=%p created %v", cp, w)
	return w
}
