// Code generated by "stringer -type=SelectResult"; DO NOT EDIT.

package rdvq

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SelectAborted-0]
	_ = x[SelectInboxEmptied-1]
	_ = x[SelectOutboxFilled-2]
}

const _SelectResult_name = "SelectAbortedSelectInboxEmptiedSelectOutboxFilled"

var _SelectResult_index = [...]uint8{0, 13, 31, 49}

func (i SelectResult) String() string {
	if i < 0 || i >= SelectResult(len(_SelectResult_index)-1) {
		return "SelectResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SelectResult_name[_SelectResult_index[i]:_SelectResult_index[i+1]]
}
