name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 5 * * 0' # run "At 05:00 on Saturday"
  workflow_dispatch:

jobs:
  build:
    uses: petenewcomb/ci-go/.github/workflows/build.yml@v0.0.1
    strategy:
      matrix:
        go: ['stable'] # drop implicit oldstable until 1.25 release

  vuln:
    uses: petenewcomb/ci-go/.github/workflows/vuln.yml@v0.0.1
