name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 5 * * 0' # run "At 05:00 on Saturday"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

jobs:
  build:
    uses: petenewcomb/ci-go/.github/workflows/build.yml@v0.0.1
  vuln:
    uses: petenewcomb/ci-go/.github/workflows/vuln.yml@v0.0.1
