name: build

permissions:
  contents: write # for coverage updates on the wiki

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 5 * * 0' # run "At 05:00 on Saturday"
  workflow_dispatch:

jobs:
  build:
    uses: petenewcomb/ci-go/.github/workflows/build.yml@v0.0.3
  vuln:
    uses: petenewcomb/ci-go/.github/workflows/vuln.yml@v0.0.3
