name: CI

permissions:
  contents: write # to update coverage report on the wiki

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 13 * * 6' # run each Saturday at 1pm UTC
  workflow_dispatch:

jobs:
  ci:
    uses: petenewcomb/ci-go/.github/workflows/ci.yml@22c7ba85cef9d711d5060d8cec08e6a8cc0e92e8
    with:
      testJobTimeoutMinutes: 30
      goTestTimeout: '25m'
