name: Release

permissions:
    contents: write # to create release

on: workflow_dispatch

jobs:
  lint:
    uses: petenewcomb/ci-go/.github/workflows/release.yml@v0.0.8
    with:
      publishDocs: true
